DEV-126040-add-suffix-prefix-for-user-agent-in-lm-data-sdk-java
logicmonitor/lm-data-sdk-java pull request #32
Opened 2023-03-15 09:14 UTC by choudharypooja

Appending applicationName as suffix to the user-agent 
More details https://confluence.logicmonitor.com/display/ENG/User-Agent+Header+from+Azure+log+ingestion
 For example applicationName is lm-logs-azure, The user-agent will now go as
 logicmonitor_data_sdk/0.0.1.alpha (Java 11.0.12;Mac OS X;arch x86_64)/lm-logs-azure

2023-03-16 05:48 UTC, mukundneharkar commented on data-sdk/build.gradle
> +    testImplementation "com.github.stefanbirkner:system-lambda:1.0.0"
No need to add another third-party library for a test case, Please remove it.

2023-03-16 11:54 UTC, mukundneharkar approved these changes

2023-03-17 06:32 UTC, lalit-fgr commented
Please resolve code target ..

2023-03-17 06:34 UTC, lalit-fgr commented on data-sdk/src/main/java/com/logicmonitor/sdk/data/ApiClientUserAgent.java
> +      applicationName = "/" + System.getenv("APPLICATION_NAME");
Not secure.. We can't open ended Env size .. it needs to be bounded to a max limit .. say 32 bytes. It can create SHELL related vulnerabilities

2023-03-17 06:35 UTC, lalit-fgr requested changes
Do the review comments

2023-03-17 07:44 UTC, choudharypooja commented
> Do the review comments
@lalit-fgr 
Adding check for max limit on the env variable and resolving build failure

2023-03-17 07:51 UTC, lalit-fgr requested changes

2023-03-17 07:51 UTC, lalit-fgr commented on data-sdk/src/main/java/com/logicmonitor/sdk/data/internal/BatchingCache.java
> +    final ApiClientUserAgent apiClient = new ApiClientUserAgent(System.getenv("APPLICATION_NAME"));
here again size restriction missing?

2023-03-17 08:43 UTC, Gaurang-Patel approved these changes

2023-03-17 10:13 UTC, lalit-fgr approved these changes
lgtm

2023-03-20 04:50 UTC, merged